In [1]:
import numpy as np

# Define the gridworld size and initialize the value function
rows, cols = 3, 4
V = np.zeros((rows, cols))

# Define the policy (directions)
# Actions: 0 = Up, 1 = Down, 2 = Left, 3 = Right
policy = [
    [0, 3, 3, 1],
    [0, None, 3, None],
    [0, 2, 2, 2]
]

# Define the rewards for each state
rewards = [
    [0, 0, 0, 1],
    [0, None, 0, -1],
    [0, 0, 0, 0]
]

# Define discount factor
gamma = 0.9

# Define the convergence threshold
theta = 0.0001

# Policy evaluation
while True:
    delta = 0
    for i in range(rows):
        for j in range(cols):
            if policy[i][j] is not None:
                v = V[i][j]
                new_v = 0
                for action in range(4):
                    if action == policy[i][j]:
                        prob = 0.7
                    else:
                        prob = 0.1
                    next_i, next_j = i, j
                    if action == 0:  # Up
                        next_i = max(i - 1, 0)
                    elif action == 1:  # Down
                        next_i = min(i + 1, rows - 1)
                    elif action == 2:  # Left
                        next_j = max(j - 1, 0)
                    elif action == 3:  # Right
                        next_j = min(j + 1, cols - 1)
                    if rewards[next_i][next_j] is not None:
                        new_v += prob * (rewards[next_i][next_j] + gamma * V[next_i][next_j])
                V[i][j] = new_v
                delta = max(delta, abs(v - new_v))
    
    if delta < theta:
        break

# Print the final value function
print("Final Value Function:")
print(V)


Final Value Function:
[[ 0.10036594  0.23751681  0.32874565 -0.57367431]
 [ 0.07561819  0.         -0.67558146  0.        ]
 [ 0.06217491  0.03735872 -0.05738241 -0.16604593]]


In [4]:
import numpy as np

# Define the gridworld size and initialize the value function
rows, cols = 3, 4
V_policy1 = np.zeros((rows, cols))
V_policy2 = np.zeros((rows, cols))

# Define the policy (directions)
# Actions: 0 = Up, 1 = Down, 2 = Left, 3 = Right
policy1 = [
    [3, 3, 3, 1],
    [0, None, 3, None],
    [0, 2, 2, 2]
]

policy2 = [
    [1, 2, 3, 1],
    [1, None, 3, None],
    [3, 1, 2, 2]
]

# Define the rewards for each state
rewards = [
    [0, 0, 0, 1],
    [0, None, 0, -1],
    [0, 0, 0, 0]
]

# Define discount factor
gamma = 0.9

# Define the convergence threshold
theta = 0.0001

# Policy evaluation for Policy 1
while True:
    delta = 0
    for i in range(rows):
        for j in range(cols):
            if policy1[i][j] is not None:
                v = V_policy1[i][j]
                new_v = 0
                for action in range(4):
                    if action == policy1[i][j]:
                        prob = 0.7
                    else:
                        prob = 0.1
                    next_i, next_j = i, j
                    if action == 0:  # Up
                        next_i = max(i - 1, 0)
                    elif action == 1:  # Down
                        next_i = min(i + 1, rows - 1)
                    elif action == 2:  # Left
                        next_j = max(j - 1, 0)
                    elif action == 3:  # Right
                        next_j = min(j + 1, cols - 1)
                    if rewards[next_i][next_j] is not None:
                        new_v += prob * (rewards[next_i][next_j] + gamma * V_policy1[next_i][next_j])
                V_policy1[i][j] = max(new_v, 0)  # Ensure values are non-negative
                delta = max(delta, abs(v - V_policy1[i][j]))
    
    if delta < theta:
        break


print("Final Value Function for Policy 1:")
print(V_policy1)

Final Value Function for Policy 1:
[[0.52563271 0.6274941  0.8312906  0.        ]
 [0.39671355 0.         0.         0.        ]
 [0.33185641 0.24672673 0.17179093 0.01002189]]


In [5]:
# Policy evaluation for Policy 2
while True:
    delta = 0
    for i in range(rows):
        for j in range(cols):
            if policy2[i][j] is not None:
                v = V_policy2[i][j]
                new_v = 0
                for action in range(4):
                    if action == policy2[i][j]:
                        prob = 0.7
                    else:
                        prob = 0.1
                    next_i, next_j = i, j
                    if action == 0:  # Up
                        next_i = max(i - 1, 0)
                    elif action == 1:  # Down
                        next_i = min(i + 1, rows - 1)
                    elif action == 2:  # Left
                        next_j = max(j - 1, 0)
                    elif action == 3:  # Right
                        next_j = min(j + 1, cols - 1)
                    if rewards[next_i][next_j] is not None:
                        new_v += prob * (rewards[next_i][next_j] + gamma * V_policy2[next_i][next_j])
                V_policy2[i][j] = max(new_v, 0)  # Ensure values are non-negative
                delta = max(delta, abs(v - V_policy2[i][j]))
    
    if delta < theta:
        break

# Print the final value functions for both policies
print("Final Value Function for Policy 1:")
print(V_policy1)
print("\nFinal Value Function for Policy 2:")
print(V_policy2)


Final Value Function for Policy 1:
[[0.52563271 0.6274941  0.8312906  0.        ]
 [0.39671355 0.         0.         0.        ]
 [0.33185641 0.24672673 0.17179093 0.01002189]]

Final Value Function for Policy 2:
[[1.00028355e-02 8.38175138e-02 7.77519866e-01 0.00000000e+00]
 [1.08007195e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.38694691e-04 3.17477470e-05 2.17072514e-05 0.00000000e+00]]


In [6]:
import numpy as np

# Define the gridworld size and initialize the value function
rows, cols = 3, 4
V_policy1 = np.zeros((rows, cols))
V_policy2 = np.zeros((rows, cols))

# Define the policy (directions)
# Actions: 0 = Up, 1 = Down, 2 = Left, 3 = Right
policy1 = [
    [0, 3, 3, 1],
    [0, None, 3, None],
    [0, 2, 2, 2]
]

policy2 = [
    [0, 2, 3, 1],
    [0, None, 3, None],
    [0, 1, 2, 2]
]

# Define the rewards for each state
rewards = [
    [0, 0, 0, 1],
    [0, None, 0, -1],
    [0, 0, 0, 0]
]

# Define discount factor
gamma = 0.9

# Define the convergence threshold
theta = 0.0001

# Policy evaluation for Policy 1
while True:
    delta = 0
    for i in range(rows):
        for j in range(cols):
            if policy1[i][j] is not None:
                v = V_policy1[i][j]
                new_v = 0
                for action in range(4):
                    if action == policy1[i][j]:
                        prob = 0.7
                    else:
                        prob = 0.1
                    next_i, next_j = i, j
                    if action == 0:  # Up
                        next_i = max(i - 1, 0)
                    elif action == 1:  # Down
                        next_i = min(i + 1, rows - 1)
                    elif action == 2:  # Left
                        next_j = max(j - 1, 0)
                    elif action == 3:  # Right
                        next_j = min(j + 1, cols - 1)
                    if rewards[next_i][next_j] is not None:
                        new_v += prob * (rewards[next_i][next_j] + gamma * V_policy1[next_i][next_j])
                V_policy1[i][j] = max(new_v, 0)  # Ensure values are non-negative
                delta = max(delta, abs(v - V_policy1[i][j]))
    
    if delta < theta:
        break

# Policy evaluation for Policy 2
while True:
    delta = 0
    for i in range(rows):
        for j in range(cols):
            if policy2[i][j] is not None:
                v = V_policy2[i][j]
                new_v = 0
                for action in range(4):
                    if action == policy2[i][j]:
                        prob = 0.7
                    else:
                        prob = 0.1
                    next_i, next_j = i, j
                    if action == 0:  # Up
                        next_i = max(i - 1, 0)
                    elif action == 1:  # Down
                        next_i = min(i + 1, rows - 1)
                    elif action == 2:  # Left
                        next_j = max(j - 1, 0)
                    elif action == 3:  # Right
                        next_j = min(j + 1, cols - 1)
                    if rewards[next_i][next_j] is not None:
                        new_v += prob * (rewards[next_i][next_j] + gamma * V_policy2[next_i][next_j])
                V_policy2[i][j] = max(new_v, 0)  # Ensure values are non-negative
                delta = max(delta, abs(v - V_policy2[i][j]))
    
    if delta < theta:
        break

# Print the final value functions for both policies in grid format
print("Final Value Function for Policy 1:")
for row in V_policy1:
    print(["{:.2f}".format(val) for val in row])

print("\nFinal Value Function for Policy 2:")
for row in V_policy2:
    print(["{:.2f}".format(val) for val in row])


Final Value Function for Policy 1:
['0.25', '0.60', '0.83', '0.00']
['0.19', '0.00', '0.00', '0.00']
['0.16', '0.12', '0.08', '0.00']

Final Value Function for Policy 2:
['0.05', '0.11', '0.78', '0.00']
['0.03', '0.00', '0.00', '0.00']
['0.03', '0.01', '0.01', '0.00']


In [9]:
import numpy as np

# Define the gridworld size and initialize the value function
rows, cols = 3, 4
V_policy1 = np.zeros((rows, cols))
V_policy2 = np.zeros((rows, cols))

# Define the policy (directions)
# Actions: 0 = Up, 1 = Down, 2 = Left, 3 = Right
policy1 = [
    [3, 3, 3, None],
    [1, None, 3, None],
    [3, 2, 0, 2]
]

policy2 = [
    [1, 2, 2, None],
    [0, None, 1, None],
    [0, 1, 2, 0]
]

# Define the rewards for each state
rewards = [
    [0, 0, 0, 1],
    [0, None, 0, -1],
    [0, 0, 0, 0]
]

# Define discount factor
gamma = 0.9

# Define the convergence threshold
theta = 0.0001

# Policy evaluation for Policy 1
while True:
    delta = 0
    for i in range(rows):
        for j in range(cols):
            if policy1[i][j] is not None:
                v = V_policy1[i][j]
                new_v = 0
                for action in range(4):
                    if action == policy1[i][j]:
                        prob = 0.7
                    else:
                        prob = 0.1
                    next_i, next_j = i, j
                    if action == 0:  # Up
                        next_i = max(i - 1, 0)
                    elif action == 1:  # Down
                        next_i = min(i + 1, rows - 1)
                    elif action == 2:  # Left
                        next_j = max(j - 1, 0)
                    elif action == 3:  # Right
                        next_j = min(j + 1, cols - 1)
                    if rewards[next_i][next_j] is not None:
                        new_v += prob * (rewards[next_i][next_j] + gamma * V_policy1[next_i][next_j])
                V_policy1[i][j] = max(new_v, 0)  # Ensure values are non-negative
                delta = max(delta, abs(v - V_policy1[i][j]))
    
    if delta < theta:
        break

# Policy evaluation for Policy 2
while True:
    delta = 0
    for i in range(rows):
        for j in range(cols):
            if policy2[i][j] is not None:
                v = V_policy2[i][j]
                new_v = 0
                for action in range(4):
                    if action == policy2[i][j]:
                        prob = 0.7
                    else:
                        prob = 0.1
                    next_i, next_j = i, j
                    if action == 0:  # Up
                        next_i = max(i - 1, 0)
                    elif action == 1:  # Down
                        next_i = min(i + 1, rows - 1)
                    elif action == 2:  # Left
                        next_j = max(j - 1, 0)
                    elif action == 3:  # Right
                        next_j = min(j + 1, cols - 1)
                    if rewards[next_i][next_j] is not None:
                        new_v += prob * (rewards[next_i][next_j] + gamma * V_policy2[next_i][next_j])
                V_policy2[i][j] = max(new_v, 0)  # Ensure values are non-negative
                delta = max(delta, abs(v - V_policy2[i][j]))
    
    if delta < theta:
        break

# Print the final value functions for both policies in a closed rectangular grid format
print("Final Value Function for Policy 1:")
for i in range(rows):
    for j in range(cols):
        print("{:.2f}".format(V_policy1[i][j]), end="\t")
    print()  # Move to the next row

print("\nFinal Value Function for Policy 2:")
for i in range(rows):
    for j in range(cols):
        print("{:.2f}".format(V_policy2[i][j]), end="\t")
    print()  # Move to the next row
------------+*

Final Value Function for Policy 1:
0.49	0.62	0.83	0.00	
0.06	0.00	0.00	0.00	
0.01	0.01	0.00	0.00	

Final Value Function for Policy 2:
0.00	0.01	0.12	0.00	
0.00	0.00	0.00	0.00	
0.00	0.00	0.00	0.00	
